#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders
mkdir -p \
    /var/run/ngircd

# copy config
if [[ ! -f /config/ngircd.conf ]]; then
    cp /defaults/ngircd.conf /config/ngircd.conf
fi

# permissions
lsiown -R abc:abc \
    /config \
    /var/run/ngircd
